# @name get-apresentation
GET http://localhost:3333

###

# @name open-the-app-by-name
GET http://localhost:3333/open-app/vlc/open

###

# @name cad-appname
POST http://localhost:3333/cad-app/:userid/user
Content-Type: application/json

{
  "prompt": "BCL-ST"
}